



// try{
//   let a = 10; 
//   // let b = 5;
//   console.log(a/b)

// } catch(error){
//    console.log(error)
// }finally
// {
//   console.log("finally is called")
// }